version: "3.4"

volumes:
  redis_data:
  postgresql_data:
  # mysql_data:
  dia_data_tmp:
  dia_data_bundle:
  dia_data_public:
  letsencrypt:
  certbot:

services:
  diaspora:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DIA_UID: "${DIASPORA_ROOT_UID}"
        DIA_GID: "${DIASPORA_ROOT_GID}"
    image: diaspora:dev-latest
    volumes:
      - "${DIASPORA_ROOT}:/diaspora:rw"
      - dia_data_tmp:/diaspora/tmp
      - dia_data_bundle:/diaspora/vendor/bundle
      - dia_data_public:/diaspora/public
    ports:
      - ${DIASPORA_DOCKER_PORT:-5000}:3000
    environment:
      - ENVIRONMENT_REDIS=redis://redis
      - SERVER_LISTEN=tcp://0.0.0.0:3000
    depends_on:
      - "${DIASPORA_DOCKER_DB}"
      - redis

  redis:
    image: redis:7
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data

  postgresql:
    image: postgres:10.3
    ports:
      - 5432:5432
    volumes:
      - postgresql_data:/var/lib/postgresql

  reverse-proxy:
    image: nginx
    volumes:
      - letsencrypt:/etc/letsencrypt/:rw
      - dia_data_public:/var/www/public
      # Env var to NGINX conf
      # https://github.com/docker-library/docs/tree/master/nginx#using-environment-variables-in-nginx-configuration-new-in-119
      - ./templates:/etc/nginx/templates
      # - certbot:/var/www/certbot:ro
    ports:
      - 80:80
      - 443:443
    environment:
      - DIASPORA_URL=${DIASPORA_URL}
  certbot:
    image: certbot/certbot
    # DNS method
    # command: certonly --manual --preferred-challenges dns -d ${DIASPORA_URL} -m mjuganaikloo@gmail.com --agree-tos --non-interactive
    # Webroot method on nginx
    command: certonly --webroot --webroot-path /var/www/certbot/ -d ${DIASPORA_URL} -m mjuganaikloo@gmail.com --agree-tos
    volumes:
      - letsencrypt:/etc/letsencrypt/:rw
      - certbot:/var/www/certbot/:rw
    depends_on:
      - reverse-proxy
    # only runs with cert profile (docker-compose --profile dev up)
    profiles: ["cert"]
     
#  mysql:
#    image: mariadb:10.2
#    ports:
    #   - 53306:3306
    # volumes:
    #   - mysql_data:/var/lib/mysql
    # environment:
    #   MYSQL_ROOT_PASSWORD: mysql
